version: '2'
services:
  web:
    build: .
    command: nginx
    ports:
      - "80:8000"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: orchardup/mysql
    environment:
      MYSQL_DATABASE: wordpress
