version: '2.0'
services:
  web:
    build: .
    command: nginx
    ports:
      - "80:80" 
      - "443:443"
      - "9000:9000"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: orchardup/mysql
    environment:
      MYSQL_DATABASE: wordpress
